import audioProtocolManifest from "../../resources/audio-protocol.json";

/**
 * The local audio boundary shared by renderer, preload, and main.
 *
 * `resources/audio-protocol.json` is the cross-language manifest. Python
 * workers intentionally keep matching local constants because packaged worker
 * runtimes must not import application TypeScript at runtime. The drift test
 * validates those constants against this manifest.
 */
export const AUDIO_PROTOCOL = Object.freeze(audioProtocolManifest);

export const AUDIO_PROTOCOL_VERSION = AUDIO_PROTOCOL.version;
export const AUDIO_SAMPLE_RATE_HZ = AUDIO_PROTOCOL.sampleRateHz;
export const AUDIO_CHANNELS = AUDIO_PROTOCOL.channels;
export const AUDIO_BITS_PER_SAMPLE = AUDIO_PROTOCOL.bitsPerSample;
export const AUDIO_BYTES_PER_SAMPLE = AUDIO_BITS_PER_SAMPLE / 8;
export const AUDIO_BYTES_PER_FRAME = AUDIO_CHANNELS * AUDIO_BYTES_PER_SAMPLE;
export const AUDIO_MAX_DURATION_MS = AUDIO_PROTOCOL.maxDurationMs;
export const AUDIO_MAX_FILE_BYTES = AUDIO_PROTOCOL.maxFileBytes;
export const AUDIO_MAX_FRAMES = (AUDIO_MAX_DURATION_MS * AUDIO_SAMPLE_RATE_HZ) / 1_000;
export const WAV_HEADER_BYTES = 44;

function hasAscii(view: DataView, offset: number, value: string): boolean {
  if (offset + value.length > view.byteLength) return false;
  for (let index = 0; index < value.length; index += 1) {
    if (view.getUint8(offset + index) !== value.charCodeAt(index)) return false;
  }
  return true;
}

/**
 * Validates the deliberately simple WAV shape generated by AudioRecorder.
 * The app does not accept ancillary WAV chunks at its IPC boundary: accepting
 * one canonical layout keeps the renderer/main and worker contracts aligned.
 */
export function isAudioProtocolWav(wav: ArrayBuffer): boolean {
  if (wav.byteLength < WAV_HEADER_BYTES || wav.byteLength > AUDIO_MAX_FILE_BYTES) return false;

  const view = new DataView(wav);
  if (
    !hasAscii(view, 0, "RIFF") ||
    !hasAscii(view, 8, "WAVE") ||
    !hasAscii(view, 12, "fmt ") ||
    !hasAscii(view, 36, "data") ||
    view.getUint32(4, true) !== wav.byteLength - 8 ||
    view.getUint32(16, true) !== 16 ||
    view.getUint16(20, true) !== 1 ||
    view.getUint16(22, true) !== AUDIO_CHANNELS ||
    view.getUint32(24, true) !== AUDIO_SAMPLE_RATE_HZ ||
    view.getUint32(28, true) !== AUDIO_SAMPLE_RATE_HZ * AUDIO_BYTES_PER_FRAME ||
    view.getUint16(32, true) !== AUDIO_BYTES_PER_FRAME ||
    view.getUint16(34, true) !== AUDIO_BITS_PER_SAMPLE
  ) {
    return false;
  }

  const dataBytes = view.getUint32(40, true);
  if (dataBytes !== wav.byteLength - WAV_HEADER_BYTES || dataBytes % AUDIO_BYTES_PER_FRAME !== 0) {
    return false;
  }
  return dataBytes / AUDIO_BYTES_PER_FRAME <= AUDIO_MAX_FRAMES;
}
